export interface FontOption {
  name: string;
  category: 'Sans Serif' | 'Serif' | 'Display' | 'Mono' | 'Handwriting';
}

export const GOOGLE_FONTS: FontOption[] = [
  // Arabic, Urdu, Persian Fonts
  { name: 'Amiri', category: 'Serif' }, // Arabic
  { name: 'Almarai', category: 'Sans Serif' }, // Arabic
  { name: 'Aref Ruqaa', category: 'Serif' }, // Arabic
  { name: 'Cairo', category: 'Sans Serif' }, // Arabic
  { name: 'Changa', category: 'Sans Serif' }, // Arabic
  { name: 'El Messiri', category: 'Sans Serif' }, // Arabic
  { name: 'Harmattan', category: 'Sans Serif' }, // Arabic
  { name: 'IBM Plex Sans Arabic', category: 'Sans Serif' }, // Arabic
  { name: 'Jomhuria', category: 'Display' }, // Arabic
  { name: 'Katibeh', category: 'Display' }, // Arabic/Persian
  { name: 'Lalezar', category: 'Display' }, // Arabic/Persian
  { name: 'Lateef', category: 'Handwriting' }, // Arabic/Urdu
  { name: 'Lemonada', category: 'Display' }, // Arabic
  { name: 'Mada', category: 'Sans Serif' }, // Arabic
  { name: 'Markazi Text', category: 'Serif' }, // Arabic/Persian
  { name: 'Mirza', category: 'Display' }, // Arabic/Urdu
  { name: 'Noto Kufi Arabic', category: 'Sans Serif' }, // Arabic
  { name: 'Noto Naskh Arabic', category: 'Serif' }, // Arabic
  { name: 'Noto Nastaliq Urdu', category: 'Serif' }, // Urdu
  { name: 'Noto Sans Arabic', category: 'Sans Serif' }, // Arabic
  { name: 'Qahiri', category: 'Sans Serif' }, // Arabic
  { name: 'Rakkas', category: 'Display' }, // Arabic
  { name: 'Reem Kufi', category: 'Sans Serif' }, // Arabic
  { name: 'Scheherazade', category: 'Serif' }, // Arabic/Urdu
  { name: 'Scheherazade New', category: 'Serif' }, // Arabic/Urdu
  { name: 'Tajawal', category: 'Sans Serif' }, // Arabic
  // Sans Serif
  { name: 'Inter', category: 'Sans Serif' },
  { name: 'Roboto', category: 'Sans Serif' },
  { name: 'Open Sans', category: 'Sans Serif' },
  { name: 'Lato', category: 'Sans Serif' },
  { name: 'Poppins', category: 'Sans Serif' },
  { name: 'Montserrat', category: 'Sans Serif' },
  { name: 'Noto Nastaliq Urdu', category: 'Sans Serif' },

  // Alphabetically ordered for easier lookup
  // Arabic, Urdu, Persian Fonts
  { name: 'Almarai', category: 'Sans Serif' },
  { name: 'Amiri', category: 'Serif' },
  { name: 'Aref Ruqaa', category: 'Serif' },
  { name: 'Cairo', category: 'Sans Serif' },
  { name: 'Changa', category: 'Sans Serif' },
  { name: 'El Messiri', category: 'Sans Serif' },
  { name: 'Harmattan', category: 'Sans Serif' },
  { name: 'IBM Plex Sans Arabic', category: 'Sans Serif' },
  { name: 'Jomhuria', category: 'Display' },
  { name: 'Katibeh', category: 'Display' },
  { name: 'Lalezar', category: 'Display' },
  { name: 'Lateef', category: 'Handwriting' },
  { name: 'Lemonada', category: 'Display' },
  { name: 'Mada', category: 'Sans Serif' },
  { name: 'Markazi Text', category: 'Serif' },
  { name: 'Mirza', category: 'Display' },
  { name: 'Noto Kufi Arabic', category: 'Sans Serif' },
  { name: 'Noto Naskh Arabic', category: 'Serif' },
  { name: 'Noto Nastaliq Urdu', category: 'Serif' },
  { name: 'Noto Sans Arabic', category: 'Sans Serif' },
  { name: 'Qahiri', category: 'Sans Serif' },
  { name: 'Rakkas', category: 'Display' },
  { name: 'Reem Kufi', category: 'Sans Serif' },
  { name: 'Scheherazade', category: 'Serif' },
  { name: 'Scheherazade New', category: 'Serif' },
  { name: 'Tajawal', category: 'Sans Serif' },

  // All Other Google Fonts (Alphabetically)
  { name: 'ABeeZee', category: 'Sans Serif' },
  { name: 'Abel', category: 'Sans Serif' },
  { name: 'Abhaya Libre', category: 'Serif' },
  { name: 'Abril Fatface', category: 'Display' },
  { name: 'Aclonica', category: 'Sans Serif' },
  { name: 'Acme', category: 'Sans Serif' },
  { name: 'Actor', category: 'Sans Serif' },
  { name: 'Adamina', category: 'Serif' },
  { name: 'Advent Pro', category: 'Sans Serif' },
  { name: 'Aguafina Script', category: 'Handwriting' },
  { name: 'Akaya Kanadaka', category: 'Display' },
  { name: 'Akaya Telivigala', category: 'Display' },
  { name: 'Akronim', category: 'Display' },
  { name: 'Aladin', category: 'Handwriting' },
  { name: 'Alata', category: 'Sans Serif' },
  { name: 'Alatsi', category: 'Sans Serif' },
  { name: 'Aldrich', category: 'Sans Serif' },
  { name: 'Alef', category: 'Sans Serif' },
  { name: 'Alegreya', category: 'Serif' },
  { name: 'Alegreya SC', category: 'Serif' },
  { name: 'Alegreya Sans', category: 'Sans Serif' },
  { name: 'Alegreya Sans SC', category: 'Sans Serif' },
  { name: 'Aleo', category: 'Serif' },
  { name: 'Alex Brush', category: 'Handwriting' },
  { name: 'Alfa Slab One', category: 'Display' },
  { name: 'Alice', category: 'Serif' },
  { name: 'Alike', category: 'Serif' },
  { name: 'Alike Angular', category: 'Serif' },
  { name: 'Allan', category: 'Display' },
  { name: 'Allerta', category: 'Sans Serif' },
  { name: 'Allerta Stencil', category: 'Sans Serif' },
  { name: 'Allison', category: 'Handwriting' },
  { name: 'Allura', category: 'Handwriting' },
  { name: 'Almendra', category: 'Serif' },
  { name: 'Almendra Display', category: 'Display' },
  { name: 'Almendra SC', category: 'Serif' },
  { name: 'Alumni Sans', category: 'Sans Serif' },
  { name: 'Amarante', category: 'Display' },
  { name: 'Amaranth', category: 'Sans Serif' },
  { name: 'Amatic SC', category: 'Handwriting' },
  { name: 'Amethysta', category: 'Serif' },
  { name: 'Amiko', category: 'Sans Serif' },
  { name: 'Amita', category: 'Handwriting' },
  { name: 'Anaheim', category: 'Sans Serif' },
  { name: 'Andada Pro', category: 'Serif' },
  { name: 'Andika', category: 'Sans Serif' },
  { name: 'Andika New Basic', category: 'Sans Serif' },
  { name: 'Angkor', category: 'Display' },
  { name: 'Annie Use Your Telescope', category: 'Handwriting' },
  { name: 'Anonymous Pro', category: 'Mono' },
  { name: 'Antic', category: 'Sans Serif' },
  { name: 'Antic Didone', category: 'Serif' },
  { name: 'Antic Slab', category: 'Serif' },
  { name: 'Anton', category: 'Sans Serif' },
  { name: 'Antonio', category: 'Sans Serif' },
  { name: 'Arapey', category: 'Serif' },
  { name: 'Arbutus', category: 'Display' },
  { name: 'Arbutus Slab', category: 'Serif' },
  { name: 'Architects Daughter', category: 'Handwriting' },
  { name: 'Archivo', category: 'Sans Serif' },
  { name: 'Archivo Black', category: 'Sans Serif' },
  { name: 'Archivo Narrow', category: 'Sans Serif' },
  { name: 'Are You Serious', category: 'Handwriting' },
  { name: 'Arima Madurai', category: 'Display' },
  { name: 'Arimo', category: 'Sans Serif' },
  { name: 'Arizonia', category: 'Handwriting' },
  { name: 'Armata', category: 'Sans Serif' },
  { name: 'Arsenal', category: 'Sans Serif' },
  { name: 'Artifika', category: 'Serif' },
  { name: 'Arvo', category: 'Serif' },
  { name: 'Arya', category: 'Sans Serif' },
  { name: 'Asap', category: 'Sans Serif' },
  { name: 'Asap Condensed', category: 'Sans Serif' },
  { name: 'Asar', category: 'Serif' },
  { name: 'Asset', category: 'Display' },
  { name: 'Assistant', category: 'Sans Serif' },
  { name: 'Astloch', category: 'Display' },
  { name: 'Asul', category: 'Sans Serif' },
  { name: 'Athiti', category: 'Sans Serif' },
  { name: 'Atkinson Hyperlegible', category: 'Sans Serif' },
  { name: 'Atma', category: 'Display' },
  { name: 'Atomic Age', category: 'Display' },
  { name: 'Aubrey', category: 'Display' },
  { name: 'Audiowide', category: 'Display' },
  { name: 'Autour One', category: 'Display' },
  { name: 'Average', category: 'Serif' },
  { name: 'Average Sans', category: 'Sans Serif' },
  { name: 'Averia Gruesa Libre', category: 'Display' },
  { name: 'Averia Libre', category: 'Display' },
  { name: 'Averia Sans Libre', category: 'Display' },
  { name: 'Averia Serif Libre', category: 'Display' },
  { name: 'Azeret Mono', category: 'Mono' },
  { name: 'B612', category: 'Sans Serif' },
  { name: 'B612 Mono', category: 'Mono' },
  { name: 'Bad Script', category: 'Handwriting' },
  { name: 'Bahiana', category: 'Display' },
  { name: 'Bahianita', category: 'Display' },
  { name: 'Bai Jamjuree', category: 'Sans Serif' },
  { name: 'Ballet', category: 'Handwriting' },
  { name: 'Baloo 2', category: 'Display' },
  { name: 'Baloo Bhai 2', category: 'Display' },
  { name: 'Baloo Bhaina 2', category: 'Display' },
  { name: 'Baloo Chettan 2', category: 'Display' },
  { name: 'Baloo Da 2', category: 'Display' },
  { name: 'Baloo Paaji 2', category: 'Display' },
  { name: 'Baloo Tamma 2', category: 'Display' },
  { name: 'Baloo Tammudu 2', category: 'Display' },
  { name: 'Baloo Thambi 2', category: 'Display' },
  { name: 'Balsamiq Sans', category: 'Display' },
  { name: 'Balthazar', category: 'Serif' },
  { name: 'Bangers', category: 'Display' },
  { name: 'Barlow', category: 'Sans Serif' },
  { name: 'Barlow Condensed', category: 'Sans Serif' },
  { name: 'Barlow Semi Condensed', category: 'Sans Serif' },
  { name: 'Barriecito', category: 'Display' },
  { name: 'Barrio', category: 'Display' },
  { name: 'Basic', category: 'Sans Serif' },
  { name: 'Baskervville', category: 'Serif' },
  { name: 'Battambang', category: 'Display' },
  { name: 'Baumans', category: 'Display' },
  { name: 'Bayon', category: 'Sans Serif' },
  { name: 'Be Vietnam', category: 'Sans Serif' },
  { name: 'Be Vietnam Pro', category: 'Sans Serif' },
  { name: 'Bebas Neue', category: 'Display' },
  { name: 'Belgrano', category: 'Serif' },
  { name: 'Bellefair', category: 'Serif' },
  { name: 'Belleza', category: 'Sans Serif' },
  { name: 'Bellota', category: 'Display' },
  { name: 'Bellota Text', category: 'Display' },
  { name: 'BenchNine', category: 'Sans Serif' },
  { name: 'Benne', category: 'Serif' },
  { name: 'Bentham', category: 'Serif' },
  { name: 'Berkshire Swash', category: 'Handwriting' },
  { name: 'Besley', category: 'Serif' },
  { name: 'Beth Ellen', category: 'Handwriting' },
  { name: 'Bevan', category: 'Display' },
  { name: 'Big Shoulders Display', category: 'Display' },
  { name: 'Big Shoulders Inline Display', category: 'Display' },
  { name: 'Big Shoulders Inline Text', category: 'Display' },
  { name: 'Big Shoulders Stencil Display', category: 'Display' },
  { name: 'Big Shoulders Stencil Text', category: 'Display' },
  { name: 'Big Shoulders Text', category: 'Display' },
  { name: 'Bigelow Rules', category: 'Display' },
  { name: 'Bigshot One', category: 'Display' },
  { name: 'Bilbo', category: 'Handwriting' },
  { name: 'Bilbo Swash Caps', category: 'Handwriting' },
  { name: 'BioRhyme', category: 'Serif' },
  { name: 'BioRhyme Expanded', category: 'Serif' },
  { name: 'Birthstone', category: 'Handwriting' },
  { name: 'Birthstone Bounce', category: 'Handwriting' },
  { name: 'Biryani', category: 'Sans Serif' },
  { name: 'Bitter', category: 'Serif' },
  { name: 'Black And White Picture', category: 'Sans Serif' },
  { name: 'Black Han Sans', category: 'Sans Serif' },
  { name: 'Black Ops One', category: 'Display' },
  { name: 'Blinker', category: 'Sans Serif' },
  { name: 'Bodoni Moda', category: 'Serif' },
  { name: 'Bokor', category: 'Display' },
  { name: 'Bona Nova', category: 'Serif' },
  { name: 'Bonbon', category: 'Handwriting' },
  { name: 'Bonheur Royale', category: 'Handwriting' },
  { name: 'Boogaloo', category: 'Display' },
  { name: 'Bowlby One', category: 'Display' },
  { name: 'Bowlby One SC', category: 'Display' },
  { name: 'Brawler', category: 'Serif' },
  { name: 'Bree Serif', category: 'Serif' },
  { name: 'Brygada 1918', category: 'Serif' },
  { name: 'Bubblegum Sans', category: 'Display' },
  { name: 'Bubbler One', category: 'Sans Serif' },
  { name: 'Buda', category: 'Display' },
  { name: 'Buenard', category: 'Serif' },
  { name: 'Bungee', category: 'Display' },
  { name: 'Bungee Hairline', category: 'Display' },
  { name: 'Bungee Inline', category: 'Display' },
  { name: 'Bungee Outline', category: 'Display' },
  { name: 'Bungee Shade', category: 'Display' },
  { name: 'Butcherman', category: 'Display' },
  { name: 'Butterfly Kids', category: 'Handwriting' },
  { name: 'Cabin', category: 'Sans Serif' },
  { name: 'Cabin Condensed', category: 'Sans Serif' },
  { name: 'Cabin Sketch', category: 'Display' },
  { name: 'Caesar Dressing', category: 'Display' },
  { name: 'Cagliostro', category: 'Sans Serif' },
  { name: 'Caladea', category: 'Serif' },
  { name: 'Calistoga', category: 'Display' },
  { name: 'Calligraffitti', category: 'Handwriting' },
  { name: 'Cambay', category: 'Sans Serif' },
  { name: 'Cambo', category: 'Serif' },
  { name: 'Candal', category: 'Sans Serif' },
  { name: 'Cantarell', category: 'Sans Serif' },
  { name: 'Cantata One', category: 'Serif' },
  { name: 'Cantora One', category: 'Sans Serif' },
  { name: 'Capriola', category: 'Sans Serif' },
  { name: 'Caramel', category: 'Handwriting' },
  { name: 'Carattere', category: 'Handwriting' },
  { name: 'Cardo', category: 'Serif' },
  { name: 'Carme', category: 'Sans Serif' },
  { name: 'Carrois Gothic', category: 'Sans Serif' },
  { name: 'Carrois Gothic SC', category: 'Sans Serif' },
  { name: 'Carter One', category: 'Display' },
  { name: 'Castoro', category: 'Serif' },
  { name: 'Catamaran', category: 'Sans Serif' },
  { name: 'Caudex', category: 'Serif' },
  { name: 'Caveat', category: 'Handwriting' },
  { name: 'Caveat Brush', category: 'Handwriting' },
  { name: 'Cedarville Cursive', category: 'Handwriting' },
  { name: 'Ceviche One', category: 'Display' },
  { name: 'Chakra Petch', category: 'Sans Serif' },
  { name: 'Changa One', category: 'Display' },
  { name: 'Chango', category: 'Display' },
  { name: 'Charm', category: 'Handwriting' },
  { name: 'Charmonman', category: 'Handwriting' },
  { name: 'Chathura', category: 'Sans Serif' },
  { name: 'Chau Philomene One', category: 'Sans Serif' },
  { name: 'Chela One', category: 'Display' },
  { name: 'Chelsea Market', category: 'Display' },
  { name: 'Chenla', category: 'Display' },
  { name: 'Cherish', category: 'Handwriting' },
  { name: 'Cherry Cream Soda', category: 'Display' },
  { name: 'Cherry Swash', category: 'Display' },
  { name: 'Chewy', category: 'Display' },
  { name: 'Chicle', category: 'Display' },
  { name: 'Chilanka', category: 'Handwriting' },
  { name: 'Chivo', category: 'Sans Serif' },
  { name: 'Chonburi', category: 'Display' },
  { name: 'Cinzel', category: 'Serif' },
  { name: 'Cinzel Decorative', category: 'Display' },
  { name: 'Clicker Script', category: 'Handwriting' },
  { name: 'Coda', category: 'Display' },
  { name: 'Coda Caption', category: 'Sans Serif' },
  { name: 'Codystar', category: 'Display' },
  { name: 'Coiny', category: 'Display' },
  { name: 'Combo', category: 'Display' },
  { name: 'Comfortaa', category: 'Display' },
  { name: 'Comic Neue', category: 'Handwriting' },
  { name: 'Coming Soon', category: 'Handwriting' },
  { name: 'Commissioner', category: 'Sans Serif' },
  { name: 'Concert One', category: 'Display' },
  { name: 'Condiment', category: 'Handwriting' },
  { name: 'Content', category: 'Display' },
  { name: 'Contrail One', category: 'Display' },
  { name: 'Convergence', category: 'Sans Serif' },
  { name: 'Cookie', category: 'Handwriting' },
  { name: 'Copse', category: 'Serif' },
  { name: 'Corben', category: 'Display' },
  { name: 'Cormorant', category: 'Serif' },
  { name: 'Cormorant Garamond', category: 'Serif' },
  { name: 'Cormorant Infant', category: 'Serif' },
  { name: 'Cormorant SC', category: 'Serif' },
  { name: 'Cormorant Unicase', category: 'Serif' },
  { name: 'Cormorant Upright', category: 'Serif' },
  { name: 'Courgette', category: 'Handwriting' },
  { name: 'Courier Prime', category: 'Mono' },
  { name: 'Cousine', category: 'Mono' },
  { name: 'Coustard', category: 'Serif' },
  { name: 'Covered By Your Grace', category: 'Handwriting' },
  { name: 'Crafty Girls', category: 'Handwriting' },
  { name: 'Creepster', category: 'Display' },
  { name: 'Crete Round', category: 'Serif' },
  { name: 'Crimson Pro', category: 'Serif' },
  { name: 'Crimson Text', category: 'Serif' },
  { name: 'Croissant One', category: 'Display' },
  { name: 'Crushed', category: 'Display' },
  { name: 'Cuprum', category: 'Sans Serif' },
  { name: 'Cute Font', category: 'Display' },
  { name: 'Cutive', category: 'Serif' },
  { name: 'Cutive Mono', category: 'Mono' },
  { name: 'DM Mono', category: 'Mono' },
  { name: 'DM Sans', category: 'Sans Serif' },
  { name: 'DM Serif Display', category: 'Serif' },
  { name: 'DM Serif Text', category: 'Serif' },
  { name: 'Damion', category: 'Handwriting' },
  { name: 'Dancing Script', category: 'Handwriting' },
  { name: 'Dangrek', category: 'Display' },
  { name: 'Darker Grotesque', category: 'Sans Serif' },
  { name: 'David Libre', category: 'Serif' },
  { name: 'Dawning of a New Day', category: 'Handwriting' },
  { name: 'Days One', category: 'Sans Serif' },
  { name: 'Dekko', category: 'Handwriting' },
  { name: 'Dela Gothic One', category: 'Display' },
  { name: 'Delius', category: 'Handwriting' },
  { name: 'Delius Swash Caps', category: 'Handwriting' },
  { name: 'Delius Unicase', category: 'Handwriting' },
  { name: 'Della Respira', category: 'Serif' },
  { name: 'Denk One', category: 'Sans Serif' },
  { name: 'Devonshire', category: 'Handwriting' },
  { name: 'Dhurjati', category: 'Sans Serif' },
  { name: 'Didact Gothic', category: 'Sans Serif' },
  { name: 'Diplomata', category: 'Display' },
  { name: 'Diplomata SC', category: 'Display' },
  { name: 'Do Hyeon', category: 'Sans Serif' },
  { name: 'Dokdo', category: 'Handwriting' },
  { name: 'Domine', category: 'Serif' },
  { name: 'Donegal One', category: 'Serif' },
  { name: 'Doppio One', category: 'Sans Serif' },
  { name: 'Dorsa', category: 'Sans Serif' },
  { name: 'Dosis', category: 'Sans Serif' },
  { name: 'DotGothic16', category: 'Sans Serif' },
  { name: 'Dr Sugiyama', category: 'Handwriting' },
  { name: 'Duru Sans', category: 'Sans Serif' },
  { name: 'Dynalight', category: 'Display' },
  { name: 'EB Garamond', category: 'Serif' },
  { name: 'Eagle Lake', category: 'Handwriting' },
  { name: 'East Sea Dokdo', category: 'Handwriting' },
  { name: 'Eater', category: 'Display' },
  { name: 'Economica', category: 'Sans Serif' },
  { name: 'Eczar', category: 'Serif' },
  { name: 'Electrolize', category: 'Sans Serif' },
  { name: 'Elsie', category: 'Display' },
  { name: 'Elsie Swash Caps', category: 'Display' },
  { name: 'Emblema One', category: 'Display' },
  { name: 'Emilys Candy', category: 'Display' },
  { name: 'Encode Sans', category: 'Sans Serif' },
  { name: 'Encode Sans Condensed', category: 'Sans Serif' },
  { name: 'Encode Sans Expanded', category: 'Sans Serif' },
  { name: 'Encode Sans SC', category: 'Sans Serif' },
  { name: 'Encode Sans Semi Condensed', category: 'Sans Serif' },
  { name: 'Encode Sans Semi Expanded', category: 'Sans Serif' },
  { name: 'Engagement', category: 'Handwriting' },
  { name: 'Englebert', category: 'Sans Serif' },
  { name: 'Enriqueta', category: 'Serif' },
  { name: 'Ephesis', category: 'Handwriting' },
  { name: 'Epilogue', category: 'Sans Serif' },
  { name: 'Erica One', category: 'Display' },
  { name: 'Esteban', category: 'Serif' },
  { name: 'Euphoria Script', category: 'Handwriting' },
  { name: 'Ewert', category: 'Display' },
  { name: 'Exo', category: 'Sans Serif' },
  { name: 'Exo 2', category: 'Sans Serif' },
  { name: 'Expletus Sans', category: 'Display' },
  { name: 'Explora', category: 'Handwriting' },
  { name: 'Fahkwang', category: 'Sans Serif' },
  { name: 'Fanwood Text', category: 'Serif' },
  { name: 'Farro', category: 'Sans Serif' },
  { name: 'Farsan', category: 'Display' },
  { name: 'Fascinate', category: 'Display' },
  { name: 'Fascinate Inline', category: 'Display' },
  { name: 'Faster One', category: 'Display' },
  { name: 'Fasthand', category: 'Handwriting' },
  { name: 'Fauna One', category: 'Serif' },
  { name: 'Faustina', category: 'Serif' },
  { name: 'Federant', category: 'Display' },
  { name: 'Federo', category: 'Sans Serif' },
  { name: 'Felipa', category: 'Handwriting' },
  { name: 'Fenix', category: 'Serif' },
  { name: 'Festive', category: 'Handwriting' },
  { name: 'Finger Paint', category: 'Display' },
  { name: 'Fira Code', category: 'Mono' },
  { name: 'Fira Mono', category: 'Mono' },
  { name: 'Fira Sans', category: 'Sans Serif' },
  { name: 'Fira Sans Condensed', category: 'Sans Serif' },
  { name: 'Fira Sans Extra Condensed', category: 'Sans Serif' },
  { name: 'Fjalla One', category: 'Sans Serif' },
  { name: 'Fjord One', category: 'Serif' },
  { name: 'Flamenco', category: 'Display' },
  { name: 'Flavors', category: 'Display' },
  { name: 'Fleur De Leah', category: 'Handwriting' },
  { name: 'Fondamento', category: 'Handwriting' },
  { name: 'Fontdiner Swanky', category: 'Display' },
  { name: 'Forum', category: 'Display' },
  { name: 'Francois One', category: 'Sans Serif' },
  { name: 'Frank Ruhl Libre', category: 'Serif' },
  { name: 'Fraunces', category: 'Serif' },
  { name: 'Freckle Face', category: 'Display' },
  { name: 'Fredericka the Great', category: 'Display' },
  { name: 'Fredoka One', category: 'Display' },
  { name: 'Freehand', category: 'Display' },
  { name: 'Fresca', category: 'Sans Serif' },
  { name: 'Frijole', category: 'Display' },
  { name: 'Fruktur', category: 'Display' },
  { name: 'Fugaz One', category: 'Display' },
  { name: 'GFS Didot', category: 'Serif' },
  { name: 'GFS Neohellenic', category: 'Sans Serif' },  
  { name: 'Gabriela', category: 'Serif' },
  { name: 'Gaegu', category: 'Handwriting' },
  { name: 'Gafata', category: 'Sans Serif' },
  { name: 'Galada', category: 'Display' },
  { name: 'Galdeano', category: 'Sans Serif' },
  { name: 'Galindo', category: 'Display' },
  { name: 'Gamja Flower', category: 'Handwriting' },
  { name: 'Gayathri', category: 'Sans Serif' },
  { name: 'Gelasio', category: 'Serif' },
  { name: 'Gentium Basic', category: 'Serif' },
  { name: 'Gentium Book Basic', category: 'Serif' },
  { name: 'Geo', category: 'Sans Serif' },
  { name: 'Geologica', category: 'Sans Serif' },
  { name: 'Georama', category: 'Sans Serif' },
  { name: 'Geostar', category: 'Display' },
  { name: 'Geostar Fill', category: 'Display' },
  { name: 'Germania One', category: 'Display' },
  { name: 'Gideon Roman', category: 'Serif' },
  { name: 'Gidugu', category: 'Sans Serif' },
  { name: 'Gilda Display', category: 'Serif' },
  { name: 'Girassol', category: 'Display' },
  { name: 'Give You Glory', category: 'Handwriting' },
  { name: 'Glass Antiqua', category: 'Display' },
  { name: 'Glegoo', category: 'Serif' },
  { name: 'Gloria Hallelujah', category: 'Handwriting' },
  { name: 'Goblin One', category: 'Display' },
  { name: 'Gochi Hand', category: 'Handwriting' },
  { name: 'Goldman', category: 'Sans Serif' },
  { name: 'Gorditas', category: 'Display' },
  { name: 'Gothic A1', category: 'Sans Serif' },
  { name: 'Gotu', category: 'Sans Serif' },
  { name: 'Goudy Bookletter 1911', category: 'Serif' },
  { name: 'Graduate', category: 'Sans Serif' },
  { name: 'Grand Hotel', category: 'Handwriting' },
  { name: 'Grandstander', category: 'Display' },
  { name: 'Gravitas One', category: 'Display' },
  { name: 'Great Vibes', category: 'Handwriting' },
  { name: 'Grechen Fuemen', category: 'Display' },
  { name: 'Grenze', category: 'Serif' },
  { name: 'Grenze Gotisch', category: 'Serif' },
  { name: 'Grey Qo', category: 'Sans Serif' },
  { name: 'Griffy', category: 'Display' },
  { name: 'Gruppo', category: 'Display' },
  { name: 'Gudea', category: 'Sans Serif' },
  { name: 'Gugi', category: 'Display' },
  { name: 'Gulzar', category: 'Serif' },
  { name: 'Gupter', category: 'Serif' },
  { name: 'Gurajada', category: 'Serif' },
  
  
  // Serif
  { name: 'Playfair Display', category: 'Serif' },
  { name: 'Merriweather', category: 'Serif' },
  { name: 'Lora', category: 'Serif' },
  { name: 'PT Serif', category: 'Serif' },
  { name: 'Crimson Text', category: 'Serif' },

  // Display
  { name: 'Oswald', category: 'Display' },
  { name: 'Bebas Neue', category: 'Display' },
  { name: 'Abril Fatface', category: 'Display' },
  { name: 'Lobster', category: 'Display' },

  // Mono
  { name: 'JetBrains Mono', category: 'Mono' },
  { name: 'Roboto Mono', category: 'Mono' },
  { name: 'Fira Code', category: 'Mono' },
  { name: 'Space Mono', category: 'Mono' },

  // Handwriting
  { name: 'Dancing Script', category: 'Handwriting' },
  { name: 'Pacifico', category: 'Handwriting' },
];

const loadedFonts = new Set<string>();

export const loadFont = (fontFamily: string) => {
  if (loadedFonts.has(fontFamily)) return;

  // Check if it's a standard web font or already loaded by other means
  if (['sans-serif', 'serif', 'Mono', 'cursive', 'fantasy', 'inherit'].includes(fontFamily.toLowerCase())) {
    return;
  }

  const linkId = `font-${fontFamily.replace(/\s+/g, '-').toLowerCase()}`;
  if (document.getElementById(linkId)) {
    loadedFonts.add(fontFamily);
    return;
  }

  const link = document.createElement('link');
  link.id = linkId;
  link.rel = 'stylesheet';
  // Request weights 300, 400, 500, 600, 700 to cover most use cases
  link.href = `https://fonts.googleapis.com/css2?family=${fontFamily.replace(/\s+/g, '+')}:wght@300;400;500;600;700&display=swap`;
  
  document.head.appendChild(link);
  loadedFonts.add(fontFamily);
};
